parameters:
  metrics_bundle.dsnDefault: redis://127.0.0.1:6379
  metrics_bundle.applicationNameDefault: unknown
  metrics_bundle.componentNameDefault: unknown

  metrics_bundle.dsn: '%env(default:metrics_bundle.dsnDefault:METRICS_STORAGE_DSN)%'
  metrics_bundle.applicationName: '%env(default:metrics_bundle.applicationNameDefault:APPLICATION_NAME)%'
  metrics_bundle.componentName: '%env(default:metrics_bundle.componentNameDefault:COMPONENT_NAME)%'

  metrics_bundle.exceptionLabelShortClassName: false
  metrics_bundle.httpClientSanitizePath: true

  metrics_bundle.metric_enums:
    - Msstc4Symfony\MetricsBundle\Infrastructure\Enum\MetricLabelEnum

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $applicationName: '%metrics_bundle.applicationName%'
      $componentName: '%metrics_bundle.componentName%'

  Msstc4Symfony\MetricsBundle\:
    resource: '../../'
    exclude:
      - '../../DependencyInjection/'
      - '../../Infrastructure/Doctrine/DBAL/'
      - '../../Infrastructure/HttpClient/HttpClientDecorator.php'
      - '../../Infrastructure/Elastica/'
      - '../../Infrastructure/Monolog/'
      - '../../MetricsBundle.php'

  Msstc4Symfony\MetricsBundle\Infrastructure\Repository\MetricRepository:
    class: Msstc4Symfony\MetricsBundle\Infrastructure\Repository\MetricRepository
    factory: ['@Msstc4Symfony\MetricsBundle\Infrastructure\Factory\MetricRepositoryFactory', create]

  Prometheus\Storage\Adapter:
    class: Prometheus\Storage\Adapter
    factory: ['@Msstc4Symfony\MetricsBundle\Infrastructure\Storage\FactoryInterface', create]
    arguments:
      $dsn: '%metrics_bundle.dsn%'

  Prometheus\RegistryInterface:
    class: Prometheus\CollectorRegistry
    arguments:
      $registerDefaultMetrics: false

  Prometheus\RendererInterface:
    class: Prometheus\RenderTextFormat
